-- UNS schema for SQLite. Mirrors setup_mysql.sql.

CREATE TABLE IF NOT EXISTS allowed_clients (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_name VARCHAR(255) NOT NULL UNIQUE,
  led INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS allowed_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(255) NOT NULL,
  domain VARCHAR(255) NOT NULL,
  tz VARCHAR(8) NOT NULL DEFAULT 'ewt:0',
  edit_urls TINYINT NOT NULL DEFAULT 1,
  edit_emerg TINYINT NOT NULL DEFAULT 1,
  edit_users TINYINT NOT NULL DEFAULT 0,
  edit_options TINYINT NOT NULL DEFAULT 0,
  c_messages TINYINT NOT NULL DEFAULT 1,
  rss_feeds TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS archive_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client VARCHAR(255) NOT NULL,
  urls TEXT NOT NULL,
  name VARCHAR(255) NOT NULL,
  details TEXT NOT NULL,
  date VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS connections (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client VARCHAR(255) NOT NULL,
  last_conn INTEGER NOT NULL,
  last_url VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS c_messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  body TEXT NOT NULL,
  refresh INTEGER NOT NULL DEFAULT 0,
  wrapper TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS emerg (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 0,
  refresh INTEGER NOT NULL DEFAULT 30
  ,scope VARCHAR(8) NOT NULL DEFAULT 'all'
  ,target VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS friendly (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  friendly VARCHAR(255) NOT NULL UNIQUE,
  client VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS hash_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  hash VARCHAR(32) NOT NULL,
  time INTEGER NOT NULL,
  username VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS internal_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  disabled TINYINT NOT NULL,
  failed INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS saved_lists (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  urls TEXT NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  details TEXT NOT NULL,
  date VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  emerg TINYINT NOT NULL DEFAULT 0,
  built_in_admin TINYINT NOT NULL DEFAULT 0,
  uns_ver VARCHAR(32) NOT NULL,
  svn_rev VARCHAR(32) NOT NULL
);

INSERT INTO settings (emerg, built_in_admin, uns_ver, svn_rev)
SELECT 0, 0, '3.1.1', '80' WHERE NOT EXISTS (SELECT 1 FROM settings);

CREATE TABLE IF NOT EXISTS rss_feeds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  maxlines INTEGER NOT NULL
);

-- General key/value settings store, see setup_mysql.sql for notes.
CREATE TABLE IF NOT EXISTS uns_config (
  cfg_key VARCHAR(64) NOT NULL PRIMARY KEY,
  cfg_value TEXT NOT NULL
);

-- Client groups, see setup_mysql.sql for notes.
CREATE TABLE IF NOT EXISTS client_groups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  mode VARCHAR(8) NOT NULL DEFAULT 'add',
  priority INTEGER NOT NULL DEFAULT 0,
  active TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS client_group_members (
  group_id INTEGER NOT NULL,
  client VARCHAR(255) NOT NULL,
  PRIMARY KEY (group_id, client)
);

CREATE TABLE IF NOT EXISTS group_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  group_id INTEGER NOT NULL,
  url VARCHAR(255) NOT NULL,
  disabled TINYINT NOT NULL DEFAULT 0,
  refresh INTEGER NOT NULL DEFAULT 60,
  UNIQUE (group_id, url)
);

-- Targeted emergency mode, see setup_mysql.sql for notes.
CREATE TABLE IF NOT EXISTS emerg_targets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scope VARCHAR(8) NOT NULL,
  target VARCHAR(255) NOT NULL,
  active TINYINT NOT NULL DEFAULT 0,
  until INTEGER NOT NULL DEFAULT 0,
  source VARCHAR(16) NOT NULL DEFAULT 'manual',
  note VARCHAR(255) NOT NULL DEFAULT '',
  updated INTEGER NOT NULL DEFAULT 0,
  UNIQUE (scope, target)
);

CREATE TABLE IF NOT EXISTS emerg_routes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL DEFAULT '',
  scope VARCHAR(8) NOT NULL DEFAULT 'all',
  target VARCHAR(255) NOT NULL DEFAULT '',
  field VARCHAR(16) NOT NULL DEFAULT 'event',
  op VARCHAR(10) NOT NULL DEFAULT 'contains',
  value VARCHAR(255) NOT NULL DEFAULT '',
  min_severity VARCHAR(16) NOT NULL DEFAULT 'Unknown',
  enabled TINYINT NOT NULL DEFAULT 1
);
